### ISSUE TITLE
includeSourceMaps: false not working

### ISSUE THREAD

**Issue by ffleandro** [FormidableLabs/tracing#17]
`includeSourceMaps` property is not working as it seems it is trying to process `.js.map` files.
Tried both with `true` and `false`, and same error is outputted.

Also, `trace-pkg` shouldn't try to process `.js.map` files, right?
The `includeSourceMaps` property is to tell it to put those files on the package and not to traverse them in search of file usages.

Logs:
```
ERROR Error: Encountered parse error in /Users/ffleandro/Workspace/node-typescript-serverless-example-service/build/src/api/acronym/acronym.router.js.map: SyntaxError: Unexpected token (1:10)
    at traceFile (/Users/ffleandro/.nvm/versions/node/v16.14.0/lib/node_modules/trace-pkg/node_modules/trace-deps/lib/trace.js:571:13)
    at async _recurseDeps (/Users/ffleandro/.nvm/versions/node/v16.14.0/lib/node_modules/trace-pkg/node_modules/trace-deps/lib/trace.js:216:22)
    at async traceFiles (/Users/ffleandro/.nvm/versions/node/v16.14.0/lib/node_modules/trace-pkg/node_modules/trace-deps/lib/trace.js:705:19)
    at async Object.bundle (/Users/ffleandro/.nvm/versions/node/v16.14.0/lib/node_modules/trace-pkg/lib/worker/bundle.js:149:48) {
  type: 'Error'
}
```

**Comment by ryan-roemer** [comment]
@ffleandro  Thanks for filing this issue. Would you be able to provide a public repository (I think this is already part of one?) exhibiting this error with install, build, and error reproduction issues? Thanks!

**Comment by ffleandro** [comment]
Thanks @ryan-roemer for your speedy response.
You can check the full code here: https://github.com/ffleandro/node-typescript-serverless-example-service
Just run `yarn build` to reproduce the described behavior

**Comment by ryan-roemer** [comment]
Thanks! Was able to reproduce very easily.

So the issue isn't the `includeSourceMaps` option, it's that your `trace` globs are pointed to a directory that includes `*.map` files (`build/src/api`).

You can either explicitly trace only JS files with:

```diff
diff --git a/build.yml b/build.yml
index 6ea1e2e..b76c4cf 100644
--- a/build.yml
+++ b/build.yml
@@ -8,7 +8,7 @@ packages:
     output: ../dist/app.zip
     trace:
       - index.js
-      - src/api
+      - src/api/**/*.js
     include:
       - src/api
       - src/server/local.js
```

or exclude the `*.map` files with:

```diff
diff --git a/build.yml b/build.yml
index 6ea1e2e..1fd3e04 100644
--- a/build.yml
+++ b/build.yml
@@ -9,6 +9,7 @@ packages:
     trace:
       - index.js
       - src/api
+      - "!src/api/**/*.map"
     include:
       - src/api
       - src/server/local.js
```

It's separately up to you if you want to set `includeSourceMaps: true` to include those `*.map` files in your output zip bundle (if `false` you'd want to remove `- src/api` from `include`)

**Comment by ffleandro** [comment]
Got it!
Thank you very much, tested and works flawlessly.

Should trace-pkg ignore `*.js.map` files by default since they are not traceable?

**Comment by ryan-roemer** [comment]
Good point! I've filed https://github.com/FormidableLabs/tracing/issues/18 to consider this. Thanks!
